import { invoke } from "../../invoke";
import type { LocationStatus, MigrationCheck, MigrationJob, AgentOptions, SummaryJob, SummaryPreview, SummarySettings, CleanupJob, CleanupPreview, DeleteJob, DeleteMode, DeletePreview, ProjectRow, Roots, RootsView, SessionDetail, SessionPage, SessionQuery, FootprintReport, WebBrowser, WebchatStatus, WebChat, WebChatDetail, WebPage, WebQuery, DistillCandidate, DistillJob, DistillPage, DistillPreview, DistillQuery, DistillResult, DistillSourceRef } from "./types";

export const listSessions = (query: SessionQuery) => invoke<SessionPage>("sessions_list", { query });
export const listProjects = () => invoke<ProjectRow[]>("sessions_projects");
export const readSession = (id: string, offset: number) => invoke<SessionDetail>("sessions_read", { id, offset });
export const getRoots = () => invoke<RootsView>("sessions_roots");
export const setRoots = (overrides: Roots) => invoke<RootsView>("sessions_set_roots", { overrides });
export const setExportDir = (path: string) => invoke<RootsView>("sessions_set_export_dir", { path });
export const setFavorite = (ids: string[], favorite: boolean) => invoke<void>("sessions_favorite", { ids, favorite });
export const openSession = (id: string, target: "folder" | "project" | "native" | "exports") => invoke<void>("sessions_open", { id, target });
export const previewDelete = (ids: string[], mode: DeleteMode) => invoke<DeletePreview>("sessions_delete_preview", { ids, mode });
export const executeDelete = (token: string) => invoke<DeleteJob>("sessions_delete_execute", { token });
export const deleteJob = () => invoke<DeleteJob | null>("sessions_job");
export const cancelDelete = () => invoke<void>("sessions_cancel");
export const scanFootprint = (refresh: boolean) => invoke<FootprintReport>("footprint_scan", { refresh });
export const previewCleanup = (ids: string[]) => invoke<CleanupPreview>("footprint_preview", { ids });
export const executeCleanup = (token: string) => invoke<CleanupJob>("footprint_execute", { token });
export const cleanupJob = () => invoke<CleanupJob | null>("footprint_job");
export const runnerOptions = () => invoke<AgentOptions[]>("runner_options");
export const getSummarySettings = () => invoke<SummarySettings>("summary_settings");
export const saveSummarySettings = (settings: SummarySettings) => invoke<void>("summary_save_settings", { settings });
export const previewSummary = (ids: string[], regenerate: boolean, settings: SummarySettings | null) => invoke<SummaryPreview>("summary_preview", { ids, regenerate, settings });
export const startSummary = (ids: string[], regenerate: boolean, settings: SummarySettings | null, locale: string) => invoke<SummaryJob>("summary_start", { ids, regenerate, settings, locale });
export const summaryJob = () => invoke<SummaryJob | null>("summary_job");
export const cancelSummary = () => invoke<void>("summary_cancel");
export const previewHandoff = (project: string, limit: number, settings: SummarySettings | null) => invoke<SummaryPreview>("handoff_preview", { project, limit, settings });
export const startHandoff = (project: string, limit: number, settings: SummarySettings | null, locale: string) => invoke<SummaryJob>("handoff_start", { project, limit, settings, locale });
export const migrationStatus = () => invoke<LocationStatus[]>("migration_status");
export const migrationCheck = (agent: string, target: string) => invoke<MigrationCheck>("migration_check", { agent, target });
export const migrationStart = (agent: string, target: string) => invoke<MigrationJob>("migration_start", { agent, target });
export const migrationDeleteBackup = (agent: string) => invoke<void>("migration_delete_backup", { agent });
export const migrationMoveBack = (agent: string) => invoke<MigrationJob>("migration_move_back", { agent });
export const migrationJob = () => invoke<MigrationJob | null>("migration_job");
export const migrationCancel = () => invoke<void>("migration_cancel");

export const webchatStatus = () => invoke<WebchatStatus>("webchat_status");
export const webchatConnect = (browser: WebBrowser) => invoke<WebchatStatus>("webchat_connect", { browser });
export const webchatDisconnect = (browser: WebBrowser) => invoke<WebchatStatus>("webchat_disconnect", { browser });
export const webchatOpen = (target: "extension" | "exports") => invoke<void>("webchat_open", { target });
export const listWebChats = (query: WebQuery) => invoke<WebPage>("webchat_list", { query });
export const readWebChat = (key: string) => invoke<WebChatDetail>("webchat_read", { key });
export const summarizeWebChat = (key: string, settings: SummarySettings | null, locale: string) => invoke<WebChat>("webchat_summarize", { key, settings, locale });
export const cancelWebSummary = () => invoke<void>("webchat_summary_cancel");

export const distillCandidates = (search: string) => invoke<DistillCandidate[]>("distill_candidates", { search });
export const previewDistill = (sources: DistillSourceRef[], settings: SummarySettings | null) => invoke<DistillPreview>("distill_preview", { sources, settings });
export const startDistill = (sources: DistillSourceRef[], kinds: string[], settings: SummarySettings | null, locale: string) => invoke<DistillJob>("distill_start", { sources, kinds, settings, locale });
export const distillJob = () => invoke<DistillJob | null>("distill_job");
export const cancelDistill = () => invoke<void>("distill_cancel");
export const listDistill = (query: DistillQuery) => invoke<DistillPage>("distill_list", { query });
export const saveDistill = (id: string, title: string, body: string) => invoke<DistillResult>("distill_save", { id, title, body });
export const setDistillState = (id: string, state: string) => invoke<DistillResult>("distill_state", { id, state });
export const deleteDistill = (id: string) => invoke<void>("distill_delete", { id });
export const exportDistill = (query: DistillQuery, locale: string) => invoke<string>("distill_export", { query, locale });
export const openDistill = (target: "skill" | "skills" | "exports", name: string) => invoke<void>("distill_open", { target, name });
