export const ERRORS: Record<string, string> = {
  E_STORAGE: "无法读写本地会话索引，请检查剩余空间和目录权限。",
  E_SCHEMA: "会话索引来自更新版本，请升级 Stacker 后重试。",
  E_CORRUPT_INDEX: "会话索引损坏，请先备份索引目录后再重建，不要删除原会话。",
  E_SOURCE_MISSING: "数据目录不存在或来源已停用，请检查数据来源。",
  E_PATH: "路径不存在或不在允许范围内，请重新选择目录。",
  E_LINK: "已跳过符号链接或目录联接，避免越界访问。",
  E_ACCESS: "目录访问被拒绝，请检查权限。",
  E_SCAN_LIMIT: "扫描范围达到安全上限，请缩小数据来源目录。",
  E_FORMAT: "无法识别此会话格式，原文件未修改。",
  E_PARTIAL: "会话存在不完整记录，仅显示可读取内容，不允许源操作或总结。",
  E_CHANGED: "会话正在写入或已发生变化，请关闭原智能体、刷新后重试。",
  E_LINE_LIMIT: "单条记录过大，当前仅显示部分内容。",
  E_FILE_LIMIT: "会话文件超过读取上限，请先导出较小的会话。",
  E_MESSAGE_LIMIT: "消息过多或过长，当前仅显示部分内容。",
  E_DUPLICATE: "发现重复来源或会话标识，请检查数据来源。",
  E_CANCELLED: "操作已取消，已完成的项目保留。",
  E_NOT_FOUND: "会话已不存在，请刷新列表。",
  E_BUSY: "已有会话任务正在执行，请等待或取消。",
  E_READ_ONLY: "此来源仅支持读取和本地整理，尚未验证原生归档与删除。",
  E_CLOSE_CODEX: "请先完全退出 Codex 桌面端和 CLI，再预览原生归档或删除。",
  E_PROCESS_CHECK: "无法确认智能体是否退出，已阻止源操作。",
  E_CODEX_MISSING: "未找到可用的 Codex CLI，请在办公智能体页安装。",
  E_CODEX_VERSION: "本机 Codex 接口版本不支持完整的影响检查，请先更新。",
  E_INCOMPLETE_SCOPE: "存在尚未索引的派生会话或路径不一致，已阻止操作，请刷新。",
  E_RPC: "Codex 接口拒绝或未完成操作，请查看任务结果后重试。",
  E_TIMEOUT: "接口响应超时，请刷新核对实际结果后再重试。",
  E_PREVIEW: "操作预览已过期或已执行，请重新预览。",
  E_VERIFY: "原客户端结果未通过核对，请刷新检查，备份已保留。",
  E_INTERRUPTED: "上次任务被中断，不会自动继续删除，请刷新核对已完成项目。",
  E_MODEL_MISSING: "请先设置总结模型。",
  E_MODEL_URL: "模型地址必须使用 HTTPS；本机服务可使用 HTTP。地址不得包含密钥或查询参数。",
  E_SECRET_STORE: "当前系统没有可用的安全密钥存储。",
  E_MODEL_NETWORK: "总结服务连接失败，请检查地址、网络和代理后重试。",
  E_MODEL_RESPONSE: "总结服务未返回有效文本，请检查模型兼容性。",
  E_SUMMARY_LIMIT: "会话超过单次总结上限，本次不截断发送。请导出后分段整理。",
  E_APPROVAL: "发送范围或模型设置已变化，请重新预览并确认。",
  E_UNSUPPORTED: "此来源暂不支持该操作。",
  E_REQUEST: "请求参数无效，请刷新后重试。",
};
export function errorMessage(error: unknown): string {
  const text = String(error);
  if (text.startsWith("E_MODEL_HTTP:")) return `HTTP ${text.split(":")[1]}`;
  return ERRORS[text] ?? text;
}
