import { openDB, type DBSchema, type IDBPDatabase } from "idb";
import type { RemoteAccount, RemoteBody, RemoteConversation, SiteId } from "../shared/types";
import { SITES } from "../sites/registry";

export interface Account { key: string; site: SiteId; remoteId: string; name: string; alias: string; lastSeen: number; localUpdatedAt: number }
export interface LocalFields { folderId: string | null; tags: string[]; favorite: boolean; note: string }
export interface Conversation extends LocalFields {
  key: string; site: SiteId; account: string; id: string; title: string;
  createdAt: number; updatedAt: number; archived: boolean;
  bodyFetchedAt: number | null; bodyUpdatedAt: number | null; removedAt: number | null;
  /** When the site's own fields (title, times, archived, removed) were last written; Stacker keeps the newest. */
  listedAt: number;
  /** When a local field (folder, tags, favorite, note) last changed; the newer copy wins on sync and restore. */
  localUpdatedAt: number;
}
export interface StoredBody extends RemoteBody { key: string }
export interface Folder { id: string; name: string; createdAt: number; localUpdatedAt: number }
export interface Excerpt { id: string; site: SiteId; conversationId: string | null; url: string; pageTitle: string; text: string; note: string; createdAt: number; localUpdatedAt: number }

/** A change waiting for Stacker. Only the record's key is queued; the current record is read when sending. */
export type OutboxKind = "account" | "conversation" | "body" | "folder" | "excerpt" | "removeFolder" | "removeExcerpt" | "all";
export interface OutboxEntry { seq?: number; kind: OutboxKind; key: string; at: number }

interface Schema extends DBSchema {
  accounts: { key: string; value: Account };
  conversations: { key: string; value: Conversation; indexes: { account: string } };
  bodies: { key: string; value: StoredBody };
  folders: { key: string; value: Folder };
  excerpts: { key: string; value: Excerpt; indexes: { conversation: [SiteId, string] } };
  outbox: { key: number; value: OutboxEntry };
}
export type Db = IDBPDatabase<Schema>;
export const DB_VERSION = 2;

export function openDb(name = "stacker-web"): Promise<Db> {
  return openDB<Schema>(name, DB_VERSION, {
    upgrade(db, oldVersion, _newVersion, tx) {
      if (oldVersion < 1) {
        db.createObjectStore("accounts", { keyPath: "key" });
        db.createObjectStore("conversations", { keyPath: "key" }).createIndex("account", "account");
        db.createObjectStore("bodies", { keyPath: "key" });
        db.createObjectStore("folders", { keyPath: "id" });
        db.createObjectStore("excerpts", { keyPath: "id" }).createIndex("conversation", ["site", "conversationId"]);
      }
      if (oldVersion < 2) {
        db.createObjectStore("outbox", { keyPath: "seq", autoIncrement: true });
        // Everything saved before sync existed goes to Stacker on the first connection.
        void tx.objectStore("outbox").add({ kind: "all", key: "", at: Date.now() });
      }
    },
  });
}

export const conversationKey = (site: SiteId, id: string) => `${site}:${id}`;
export const accountKey = (site: SiteId, remoteId: string) => `${site}:${remoteId}`;
const newId = () => crypto.randomUUID();
/** Records saved before version 2 have no sync times; they count as oldest. */
const stamp = (value: number | undefined) => value ?? 0;

let outboxListener: (() => void) | null = null;
/** Pages and the background say how to start a sync after a local change. */
export function onOutboxChange(listener: (() => void) | null): void { outboxListener = listener; }
const changed = () => outboxListener?.();

type OutboxWriter = { add(value: OutboxEntry): Promise<unknown> };
async function enqueue(store: OutboxWriter, kind: OutboxKind, keys: string[], at: number): Promise<void> {
  for (const key of keys) await store.add({ kind, key, at });
}

/** A stored alias auto-generated by an older version, back when it stood in for the site name. */
const AUTO_ALIAS = /^(ChatGPT|Claude)( \d+)?$/;

/** Records saved before `name` existed: an alias that was really just the site label becomes no alias at all. */
function migrateAccount(a: Account, site: SiteId): Account {
  const synced = { ...a, localUpdatedAt: stamp(a.localUpdatedAt) };
  if (typeof a.name === "string" && a.name) return synced;
  return { ...synced, name: SITES[site].label, alias: AUTO_ALIAS.test(a.alias) ? "" : a.alias };
}

export async function upsertAccount(db: Db, site: SiteId, remote: RemoteAccount, now: number): Promise<Account> {
  const key = accountKey(site, remote.remoteId);
  const tx = db.transaction(["accounts", "outbox"], "readwrite");
  const existing = await tx.objectStore("accounts").get(key);
  const name = remote.label || SITES[site].label;
  const account: Account = existing
    ? { ...migrateAccount(existing, site), name, lastSeen: now }
    : { key, site, remoteId: remote.remoteId, name, alias: "", lastSeen: now, localUpdatedAt: 0 };
  await tx.objectStore("accounts").put(account);
  const queued = !existing || existing.name !== name;
  if (queued) await enqueue(tx.objectStore("outbox"), "account", [key], now);
  await tx.done;
  if (queued) changed();
  return account;
}

export async function listAccounts(db: Db): Promise<Account[]> {
  return (await db.getAll("accounts")).map((a) => migrateAccount(a, a.site));
}

/** The name shown for an account: the user's own alias when set, else the site's latest name for it. */
export function accountDisplayName(a: Account): string {
  return a.alias || a.name;
}

export async function renameAccount(db: Db, key: string, alias: string, now = Date.now()): Promise<void> {
  const tx = db.transaction(["accounts", "outbox"], "readwrite");
  const a = await tx.objectStore("accounts").get(key);
  if (a) {
    await tx.objectStore("accounts").put({ ...migrateAccount(a, a.site), alias: alias.trim(), localUpdatedAt: now });
    await enqueue(tx.objectStore("outbox"), "account", [key], now);
  }
  await tx.done;
  if (a) changed();
}

/** Refreshes titles and times, keeps local fields; a complete listing marks the rest removed. */
export async function mergeListing(db: Db, account: Account, items: RemoteConversation[], complete: boolean, now: number) {
  const tx = db.transaction(["conversations", "outbox"], "readwrite");
  const store = tx.objectStore("conversations");
  const counts = { added: 0, updated: 0, removed: 0 };
  const seen = new Set<string>();
  const queued: string[] = [];
  for (const item of items) {
    const key = conversationKey(account.site, item.id);
    seen.add(key);
    const old = await store.get(key);
    if (!old) { counts.added++; queued.push(key); }
    else if (old.updatedAt !== item.updatedAt || old.title !== item.title || old.archived !== item.archived || old.removedAt !== null) {
      counts.updated++;
      queued.push(key);
    }
    await store.put({
      folderId: null, tags: [], favorite: false, note: "", bodyFetchedAt: null, bodyUpdatedAt: null, localUpdatedAt: 0,
      ...old,
      key, site: account.site, account: account.key, id: item.id, title: item.title,
      createdAt: item.createdAt, updatedAt: item.updatedAt, archived: item.archived, removedAt: null, listedAt: now,
    });
  }
  if (complete) {
    for (const c of await store.index("account").getAll(account.key)) {
      if (!seen.has(c.key) && c.removedAt === null) {
        counts.removed++;
        queued.push(c.key);
        await store.put({ ...c, removedAt: now, listedAt: now });
      }
    }
  }
  await enqueue(tx.objectStore("outbox"), "conversation", queued, now);
  await tx.done;
  if (queued.length) changed();
  return counts;
}

export const listConversations = (db: Db) => db.getAll("conversations");
export const getConversation = (db: Db, key: string) => db.get("conversations", key);

export async function updateLocal(db: Db, keys: string[], patch: Partial<LocalFields>, now = Date.now()): Promise<void> {
  const tx = db.transaction(["conversations", "outbox"], "readwrite");
  const store = tx.objectStore("conversations");
  const queued: string[] = [];
  for (const key of keys) {
    const c = await store.get(key);
    if (c) { await store.put({ ...c, ...patch, localUpdatedAt: now }); queued.push(key); }
  }
  await enqueue(tx.objectStore("outbox"), "conversation", queued, now);
  await tx.done;
  if (queued.length) changed();
}

export async function addTag(db: Db, keys: string[], tag: string, now = Date.now()): Promise<void> {
  const clean = tag.trim();
  if (!clean) return;
  const tx = db.transaction(["conversations", "outbox"], "readwrite");
  const store = tx.objectStore("conversations");
  const queued: string[] = [];
  for (const key of keys) {
    const c = await store.get(key);
    if (c && !c.tags.includes(clean)) { await store.put({ ...c, tags: [...c.tags, clean], localUpdatedAt: now }); queued.push(key); }
  }
  await enqueue(tx.objectStore("outbox"), "conversation", queued, now);
  await tx.done;
  if (queued.length) changed();
}

export async function putBody(db: Db, key: string, body: RemoteBody, now: number): Promise<void> {
  const tx = db.transaction(["bodies", "conversations", "outbox"], "readwrite");
  await tx.objectStore("bodies").put({ ...body, key });
  const c = await tx.objectStore("conversations").get(key);
  // The body was just fetched live, so it is at least as new as whatever updatedAt the listing
  // held then: some sites (Grok, Gemini) compute the listing's updatedAt from a different field
  // than the body's own latest-message time, so the two can otherwise never agree.
  if (c) await tx.objectStore("conversations").put({ ...c, bodyFetchedAt: now, bodyUpdatedAt: Math.max(body.updatedAt, c.updatedAt) });
  await enqueue(tx.objectStore("outbox"), "body", [key], now);
  await tx.done;
  changed();
}

export const getBody = (db: Db, key: string) => db.get("bodies", key);

export function bodyIsFresh(c: Conversation): boolean {
  return c.bodyUpdatedAt !== null && c.bodyUpdatedAt >= c.updatedAt;
}

export async function markRemoved(db: Db, key: string, now: number): Promise<void> {
  const tx = db.transaction(["conversations", "outbox"], "readwrite");
  const c = await tx.objectStore("conversations").get(key);
  if (c) {
    await tx.objectStore("conversations").put({ ...c, removedAt: now, listedAt: now });
    await enqueue(tx.objectStore("outbox"), "conversation", [key], now);
  }
  await tx.done;
  if (c) changed();
}

export const listFolders = (db: Db) => db.getAll("folders");

export async function createFolder(db: Db, name: string, now: number): Promise<Folder> {
  const folder = { id: newId(), name: name.trim(), createdAt: now, localUpdatedAt: now };
  const tx = db.transaction(["folders", "outbox"], "readwrite");
  await tx.objectStore("folders").put(folder);
  await enqueue(tx.objectStore("outbox"), "folder", [folder.id], now);
  await tx.done;
  changed();
  return folder;
}

export async function renameFolder(db: Db, id: string, name: string, now = Date.now()): Promise<void> {
  if (!name.trim()) return;
  const tx = db.transaction(["folders", "outbox"], "readwrite");
  const f = await tx.objectStore("folders").get(id);
  if (f) {
    await tx.objectStore("folders").put({ ...f, name: name.trim(), localUpdatedAt: now });
    await enqueue(tx.objectStore("outbox"), "folder", [id], now);
  }
  await tx.done;
  if (f) changed();
}

export async function deleteFolder(db: Db, id: string, now = Date.now()): Promise<void> {
  const tx = db.transaction(["folders", "conversations", "outbox"], "readwrite");
  await tx.objectStore("folders").delete(id);
  const released: string[] = [];
  for (const c of await tx.objectStore("conversations").getAll()) {
    if (c.folderId === id) {
      await tx.objectStore("conversations").put({ ...c, folderId: null, localUpdatedAt: now });
      released.push(c.key);
    }
  }
  const outbox = tx.objectStore("outbox");
  await enqueue(outbox, "removeFolder", [id], now);
  await enqueue(outbox, "conversation", released, now);
  await tx.done;
  changed();
}

export async function addExcerpt(db: Db, e: Omit<Excerpt, "id" | "createdAt" | "localUpdatedAt">, now: number): Promise<Excerpt> {
  const excerpt = { ...e, id: newId(), createdAt: now, localUpdatedAt: now };
  const tx = db.transaction(["excerpts", "outbox"], "readwrite");
  await tx.objectStore("excerpts").put(excerpt);
  await enqueue(tx.objectStore("outbox"), "excerpt", [excerpt.id], now);
  await tx.done;
  changed();
  return excerpt;
}

export async function listExcerpts(db: Db, site?: SiteId, conversationId?: string): Promise<Excerpt[]> {
  let all: Excerpt[];
  if (site && conversationId) {
    all = await db.getAllFromIndex("excerpts", "conversation", [site, conversationId]);
  } else if (site) {
    const allExcerpts = await db.getAll("excerpts");
    all = allExcerpts.filter((e) => e.site === site);
  } else {
    all = await db.getAll("excerpts");
  }
  return all.sort((a, b) => b.createdAt - a.createdAt);
}

export async function deleteExcerpt(db: Db, id: string, now = Date.now()): Promise<void> {
  const tx = db.transaction(["excerpts", "outbox"], "readwrite");
  await tx.objectStore("excerpts").delete(id);
  await enqueue(tx.objectStore("outbox"), "removeExcerpt", [id], now);
  await tx.done;
  changed();
}

export const outboxCount = (db: Db) => db.count("outbox");
export const readOutbox = (db: Db, limit: number) => db.getAll("outbox", undefined, limit);

export async function dropOutbox(db: Db, seqs: number[]): Promise<void> {
  if (!seqs.length) return;
  const tx = db.transaction("outbox", "readwrite");
  for (const seq of seqs) await tx.store.delete(seq);
  await tx.done;
}

/** Sends everything again, e.g. when Stacker's copy is empty. At most one such entry waits at a time. */
export async function enqueueAll(db: Db, now: number): Promise<void> {
  const tx = db.transaction("outbox", "readwrite");
  let waiting = false;
  for (let cursor = await tx.store.openCursor(); cursor; cursor = await cursor.continue()) {
    if (cursor.value.kind === "all") { waiting = true; break; }
  }
  if (!waiting) await tx.store.add({ kind: "all", key: "", at: now });
  await tx.done;
  if (!waiting) changed();
}

export interface Backup {
  accounts: Account[];
  folders: Folder[];
  conversations: Omit<Conversation, "bodyFetchedAt" | "bodyUpdatedAt">[];
  excerpts: Excerpt[];
}
export interface RestoreCounts { accounts: number; folders: number; conversations: number; excerpts: number }

const knownSite = (site: string): site is SiteId => Object.prototype.hasOwnProperty.call(SITES, site);

/**
 * Brings organizing data back from Stacker: missing records are added, and a record's local
 * fields change only where Stacker's copy is newer. Nothing is queued, since it came from Stacker.
 */
export async function applyBackup(db: Db, backup: Backup): Promise<RestoreCounts> {
  const tx = db.transaction(["accounts", "folders", "conversations", "excerpts"], "readwrite");
  const counts: RestoreCounts = { accounts: 0, folders: 0, conversations: 0, excerpts: 0 };
  const accounts = tx.objectStore("accounts");
  for (const a of backup.accounts.filter((x) => knownSite(x.site))) {
    const local = await accounts.get(a.key);
    if (!local) { await accounts.put(a); counts.accounts++; }
    else if (a.localUpdatedAt > stamp(local.localUpdatedAt)) {
      await accounts.put({ ...local, alias: a.alias, localUpdatedAt: a.localUpdatedAt });
      counts.accounts++;
    }
  }
  const folders = tx.objectStore("folders");
  for (const f of backup.folders) {
    const local = await folders.get(f.id);
    if (!local) { await folders.put(f); counts.folders++; }
    else if (f.localUpdatedAt > stamp(local.localUpdatedAt)) {
      await folders.put({ ...local, name: f.name, localUpdatedAt: f.localUpdatedAt });
      counts.folders++;
    }
  }
  const conversations = tx.objectStore("conversations");
  for (const c of backup.conversations.filter((x) => knownSite(x.site))) {
    const local = await conversations.get(c.key);
    if (!local) { await conversations.put({ ...c, bodyFetchedAt: null, bodyUpdatedAt: null }); counts.conversations++; }
    else if (c.localUpdatedAt > stamp(local.localUpdatedAt)) {
      await conversations.put({ ...local, folderId: c.folderId, tags: c.tags, favorite: c.favorite, note: c.note, localUpdatedAt: c.localUpdatedAt });
      counts.conversations++;
    }
  }
  const excerpts = tx.objectStore("excerpts");
  for (const e of backup.excerpts.filter((x) => knownSite(x.site))) {
    const local = await excerpts.get(e.id);
    if (!local) { await excerpts.put(e); counts.excerpts++; }
    else if (e.localUpdatedAt > stamp(local.localUpdatedAt)) {
      await excerpts.put({ ...local, text: e.text, note: e.note, localUpdatedAt: e.localUpdatedAt });
      counts.excerpts++;
    }
  }
  await tx.done;
  return counts;
}
